import type { Language } from './types';

export const translations: Record<Language, any> = {
  en: {
    title: 'Seizure Alert',
    subtitle: 'Press the button below if you feel a seizure starting.',
    emergencyButton: 'EMERGENCY',
    alertTitle: 'MEDICAL EMERGENCY',
    alertStatus: 'I am having a seizure. I am not in control.',
    durationLabel: 'DURATION',
    instructionsTitle: 'Instructions for Bystanders',
    instructions: [
      'Stay calm. I should be okay in a few minutes.',
      'Time the seizure. Call 911 if it lasts more than 5 minutes.',
      'Keep me safe. Move sharp objects away.',
      'Gently roll me onto my side to help with breathing.',
      'Cushion my head with something soft.',
      'Do NOT hold me down or restrict my movements.',
      'Do NOT put anything in my mouth.',
      'Stay with me until the seizure is over and I am fully awake.',
    ],
    ttsIntro: 'A medical emergency is in progress. Please follow these instructions.',
    emergencyContacts: 'Emergency Contacts',
    noContactsMessage: 'No emergency contacts have been added. Please add them in Settings.',
    imOkButton: "I'm OK",
    sirenMute: 'Mute siren',
    sirenUnmute: 'Unmute siren',
    aiButton: 'AI',
    chatTitle: 'Aura Health Assistant',
    chatPlaceholder: 'Type your message...',
    chatMicListening: 'Listening...',
    chatMicError: 'Mic error, please type.',
    chatInitialGreeting: "Hello! I'm Aura. I can provide information on seizure first aid. How can I help? Note: I am not a medical professional.",
    settingsTitle: 'Settings',
    settingsContacts: 'Contacts',
    settingsAPIKey: 'API Key',
    settingsAddContact: 'Add Contact',
    settingsContactName: 'Name',
    settingsContactRelation: 'Relation (e.g., Spouse)',
    settingsContactPhone: 'Phone Number',
    settingsSave: 'Save',
    settingsCancel: 'Cancel',
    settingsAPIKeyLabel: 'Gemini API Key',
    settingsAPIKeyPlaceholder: 'Enter your API key',
    settingsAPIKeyDesc: "Aura AI features require a Gemini API Key. Get one from Google AI Studio. Your key is saved only on this device.",
    chatAPIKeyMissing: "Please add your Gemini API Key in settings to use Aura.",
    settingsPatientInfo: "Patient Information",
    settingsPatientName: "Patient Name",
    settingsBloodType: "Blood Type",
    settingsMedicalConditions: "Medical Conditions / Allergies",
    settingsBloodTypePlaceholder: "Select Blood Type",
    aboutTitle: "My Story, My Mission",
    aboutOriginTitle: "The Medellin Incident",
    aboutStory: "I had a near seizure... I was eating a sandwich and a coffee in the airport in Medellin, when suddenly it hit me. I didn't have a way to express myself, words went away. I pulled my phone but to call who? My girlfriend an hour away? I needed to communicate but my mind had thousands of thoughts and déjá vus, unable to find the word 'seizure'. I drank my coffee rapidly and the symptoms faded a bit and I was able to stabilize. All I needed in that moment was a Button to press and others to be able to identify what was happening.",
    aboutMissionTitle: "Our Mission",
    aboutMissionText: "This is not a medical app but a tool to inspire and help potentially others. Please read our full disclosure.",
    aboutReadDisclosure: "Read Full Disclosure",
    aboutConnectTitle: "Connect with the Creator",
    aboutCompanyTitle: "My Company",
    reportsTitle: "Alert History",
    openReports: "Open Alert History",
    noReportsMessage: "No alert history has been recorded yet.",
    reportDurationLabel: "Duration",
    reportNotesLabel: "Notes",
    addNotes: "Add Notes",
    editNotes: "Edit Notes",
    saveNotes: "Save Notes",
    cancelNotes: "Cancel",
    deleteReport: "Delete Report",
    notesPlaceholder: "Add notes about this event (e.g., potential triggers, feelings)...",
    autoCalling: "Automatically calling",
    slideToCancel: "Slide to Cancel",
    callCancelled: "Automatic call was cancelled.",
    callInitiated: "Automatic call initiated.",
    inSeconds: "in",
    secondsShort: "s",
    disclaimerTitle: "Medical Disclaimer",
    disclaimerImportant: "Important:",
    disclaimerText1: "This application is for informational purposes only.",
    disclaimerText2: "This application is NOT a certified medical device. It is intended as an informational tool to assist in attracting attention and providing guidance to bystanders during a potential medical event.",
    disclaimerText3: "It should not be solely relied upon for emergency situations. In case of a medical emergency, always call your local emergency services immediately.",
    disclaimerText4: "The developer assumes no liability for the use or misuse of this application. Is stored locally.",
    disclaimerButton: "I Understand",
  },
  es: {
    title: 'Alerta de Convulsión',
    subtitle: 'Presiona el botón de abajo si sientes que comienza una convulsión.',
    emergencyButton: 'EMERGENCIA',
    alertTitle: 'EMERGENCIA MÉDICA',
    alertStatus: 'Estoy teniendo una convulsión. No estoy en control.',
    durationLabel: 'DURACIÓN',
    instructionsTitle: 'Instrucciones para Testigos',
    instructions: [
      'Mantén la calma. Estaré bien en unos minutos.',
      'Cronometra la convulsión. Llama al 911 si dura más de 5 minutos.',
      'Mantenme a salvo. Aleja los objetos afilados.',
      'Gírame suavemente de lado para ayudarme a respirar.',
      'Amortigua mi cabeza con algo suave.',
      'NO me sujetes ni restrinjas mis movimientos.',
      'NO pongas nada en mi boca.',
      'Quédate conmigo hasta que termine la convulsión y esté completamente despierto.',
    ],
    ttsIntro: 'Una emergencia médica está en curso. Por favor, siga estas instrucciones.',
    emergencyContacts: 'Contactos de Emergencia',
    noContactsMessage: 'No se han añadido contactos de emergencia. Por favor, añádelos en Configuración.',
    imOkButton: 'Estoy Bien',
    sirenMute: 'Silenciar sirena',
    sirenUnmute: 'Activar sirena',
    aiButton: 'IA',
    chatTitle: 'Asistente de Salud Aura',
    chatPlaceholder: 'Escribe tu mensaje...',
    chatMicListening: 'Escuchando...',
    chatMicError: 'Error de micrófono, por favor escribe.',
    chatInitialGreeting: '¡Hola! Soy Aura. Puedo proporcionar información sobre primeros auxilios para convulsiones. ¿Cómo puedo ayudar? Nota: No soy un profesional médico.',
    settingsTitle: 'Configuración',
    settingsContacts: 'Contactos',
    settingsAPIKey: 'Clave API',
    settingsAddContact: 'Añadir Contacto',
    settingsContactName: 'Nombre',
    settingsContactRelation: 'Relación (ej. Esposo/a)',
    settingsContactPhone: 'Número de Teléfono',
    settingsSave: 'Guardar',
    settingsCancel: 'Cancelar',
    settingsAPIKeyLabel: 'Clave API de Gemini',
    settingsAPIKeyPlaceholder: 'Introduce tu clave API',
    settingsAPIKeyDesc: "Las funciones de IA de Aura requieren una clave API de Gemini. Obtén una en Google AI Studio. Tu clave se guarda solo en este dispositivo.",
    chatAPIKeyMissing: "Por favor, añade tu clave API de Gemini en la configuración para usar Aura.",
    settingsPatientInfo: "Información del Paciente",
    settingsPatientName: "Nombre del Paciente",
    settingsBloodType: "Tipo de Sangre",
    settingsMedicalConditions: "Condiciones Médicas / Alergias",
    settingsBloodTypePlaceholder: "Seleccionar Tipo de Sangre",
    reportsTitle: "Historial de Alertas",
    openReports: "Abrir Historial de Alertas",
    noReportsMessage: "Aún no se ha registrado ningún historial de alertas.",
    reportDurationLabel: "Duración",
    reportNotesLabel: "Notas",
    addNotes: "Añadir Notas",
    editNotes: "Editar Notas",
    saveNotes: "Guardar Notas",
    cancelNotes: "Cancelar",
    deleteReport: "Eliminar Reporte",
    notesPlaceholder: "Añade notas sobre este evento (ej. posibles desencadenantes, sentimientos)...",
    aboutTitle: "Mi Historia, Mi Misión",
    aboutOriginTitle: "El Incidente de Medellín",
    aboutStory: "Tuve una casi convulsión... Estaba comiendo un sándwich y un café en el aeropuerto de Medellín, cuando de repente me golpeó. No tenía forma de expresarme, las palabras se fueron. Saqué mi teléfono pero ¿a quién llamar? ¿A mi novia a una hora de distancia? Necesitaba comunicarme pero mi mente tenía miles de pensamientos y déjá vus, incapaz de encontrar la palabra 'convulsión'. Bebí mi café rápidamente y los síntomas se desvanecieron un poco y pude estabilizarme. Todo lo que necesitaba en ese momento era un Botón para presionar y que otros pudieran identificar lo que estaba sucediendo.",
    aboutMissionTitle: "Nuestra Misión",
    aboutMissionText: "Esta no es una aplicación médica, sino una herramienta para inspirar y ayudar potencialmente a otros. Por favor lea nuestra divulgación completa.",
    aboutReadDisclosure: "Leer Divulgación Completa",
    aboutConnectTitle: "Conecta con el Creador",
    aboutCompanyTitle: "Mi Compañía",
    autoCalling: "Llamando automáticamente a",
    slideToCancel: "Deslizar para Cancelar",
    callCancelled: "Llamada automática cancelada.",
    callInitiated: "Llamada automática iniciada.",
    inSeconds: "en",
    secondsShort: "s",
    disclaimerTitle: "Aviso Médico",
    disclaimerImportant: "Importante:",
    disclaimerText1: "Esta aplicación es solo para fines informativos.",
    disclaimerText2: "Esta aplicación NO es un dispositivo médico certificado. Está destinada a ser una herramienta informativa para ayudar a atraer la atención y proporcionar orientación a los transeúntes durante un posible evento médico.",
    disclaimerText3: "No debe depender únicamente de ella para situaciones de emergencia. En caso de una emergencia médica, llame siempre a los servicios de emergencia locales de inmediato.",
    disclaimerText4: "El desarrollador no asume ninguna responsabilidad por el uso o mal uso de esta aplicación. Se almacena localmente.",
    disclaimerButton: "Entiendo",
  },
};

export const getSystemPrompt = (language: Language): string => `
  You are Aura, a compassionate AI assistant specialized in seizure first aid.
  Your goal is to provide clear, simple, and calm information.
  You MUST NOT provide any medical advice, diagnosis, or treatment plans.
  If asked for medical advice, you MUST politely decline and strongly recommend consulting a healthcare professional or emergency services.
  You MUST respond exclusively in the following language: ${language === 'es' ? 'Spanish' : 'English'}.
  Keep your answers concise and easy to understand.
`;