import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AlertReport, Language } from '../types';
import { translations } from '../constants';

export const generateSeizureReport = (reports: AlertReport[], language: Language) => {
    const t = translations[language];
    const doc = new jsPDF();

    // Title
    doc.setFontSize(22);
    doc.text(t.title || 'Seizure Alert', 14, 20);

    doc.setFontSize(14);
    doc.text('Seizure Report', 14, 30);

    doc.setFontSize(10);
    const dateStr = new Date().toLocaleDateString();
    doc.text(`Generated on: ${dateStr}`, 14, 38);

    // Table Data
    const tableBody = reports.map(report => [
        new Date(report.date).toLocaleDateString(),
        new Date(report.date).toLocaleTimeString(),
        report.duration ? `${Math.floor(report.duration / 60)}m ${report.duration % 60}s` : 'N/A',
        report.notes || 'No notes'
    ]);

    // Generate Table
    autoTable(doc, {
        startY: 45,
        head: [['Date', 'Time', 'Duration', 'Notes']],
        body: tableBody,
        foot: [['', '', '', '']], // Placeholder for footer
        margin: { bottom: 30 }, // Leave room for custom footer
        didDrawPage: (data) => {
            // Footer Logic
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();

            doc.setFontSize(8);
            doc.setTextColor(128, 128, 128); // Gray color

            // Disclaimer
            const disclaimer = "DISCLAIMER: This report is generated by a software application and is not a medical device. It should not be used for diagnosis or treatment. Always consult a healthcare professional.";
            const splitDisclaimer = doc.splitTextToSize(disclaimer, doc.internal.pageSize.width - 30);
            doc.text(splitDisclaimer, 14, pageHeight - 20);

            // Website Branding
            doc.setFontSize(10);
            doc.setTextColor(0, 0, 255); // Blue
            doc.textWithLink('RamonRios.NET', 14, pageHeight - 10, { url: 'https://ramonrios.net' });

            doc.setTextColor(128, 128, 128); // Reset to gray for page number
            const pageCount = 'Page ' + doc.getNumberOfPages();
            // Right align page number
            const pageWidth = pageSize.width ? pageSize.width : pageSize.getWidth();
            doc.text(pageCount, pageWidth - 14 - doc.getTextWidth(pageCount), pageHeight - 10);
        }
    });

    // Save/Download
    const fileName = `Seizure_Report_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
};
